Traceback (most recent call last):
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import json
from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient
from azure.search.documents.models import (
    VectorizedQuery
)
from azure.search.documents.indexes.models import (
    SearchIndex,
    ScoringProfile,
    SearchFieldDataType,
    SimpleField,
    SearchableField,
    SearchField,
    SemanticConfiguration,
    SemanticField,
    VectorSearchProfile,
    HnswAlgorithmConfiguration,
    VectorSearch,
    HnswParameters,
    SemanticPrioritizedFields,
    SemanticSearch,
)
from azure.search.documents.indexes import SearchIndexClient
import os.path

# subscription_id = os.environ["subscription_id"]
# resource_group_name = os.environ["resource_group_name"]
# workspace_name = os.environ["workspace_name"]
service_endpoint = os.environ[
    "service_endpoint"
]  # the endpoint of your Azure Cognitive Search service
key = os.environ["search_key"]

# aoai_connection_name = os.environ['aoai_connection_name']
aoi_deployment_name = os.environ["AZURE_OPENAI_DEPLOYMENT_NAME"]
azure_openai_key = os.environ["azure_openai_key"]
azure_aoai_endpoint = os.environ["azure_aoai_endpoint"]
embedding_model_name = os.environ["azure_openai_embedding_deployment"]

search_index_name = "index_chunks_2"
search_index_key = os.getenv("AZURE_SEARCH_ADMIN_KEY")
credential = AzureKeyCredential(key)
storage_account_connection_string = os.getenv("storage_account_connection_string")
azure_openai_embedding_deployment = os.getenv("azure_openai_embedding_deployment")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
Cell [1;32mIn[3], line 30[0m
[0;32m     25[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpath[39;00m
[0;32m     27[0m [38;5;66;03m# subscription_id = os.environ["subscription_id"][39;00m
[0;32m     28[0m [38;5;66;03m# resource_group_name = os.environ["resource_group_name"][39;00m
[0;32m     29[0m [38;5;66;03m# workspace_name = os.environ["workspace_name"][39;00m
[1;32m---> 30[0m service_endpoint [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43menviron[49m[43m[[49m
[0;32m     31[0m [43m    [49m[38;5;124;43m"[39;49m[38;5;124;43mservice_endpoint[39;49m[38;5;124;43m"[39;49m
[0;32m     32[0m [43m][49m  [38;5;66;03m# the endpoint of your Azure Cognitive Search service[39;00m
[0;32m     33[0m key [38;5;241m=[39m os[38;5;241m.[39menviron[[38;5;124m"[39m[38;5;124msearch_key[39m[38;5;124m"[39m]
[0;32m     35[0m [38;5;66;03m# aoai_connection_name = os.environ['aoai_connection_name'][39;00m

File [1;32m<frozen os>:685[0m, in [0;36m__getitem__[1;34m(self, key)[0m

[1;31mKeyError[0m: 'service_endpoint'

